### ISSUE TITLE
After deployment - sorting attendees logs me out

### ISSUE THREAD

**Issue by LiviaButtons** [WPChill/rsvp#76]
Deployed to prod environment, and encountered a new issue. When I try to sort the attendees (e.g. by RSVP status) I am instead logged out of the admin dashboard. Didn't previously have this in local environment. Perhaps db naming shaenanigans again?

**Comment by GitSlinger** [comment]
I've found this too. I've had this running on my wedding website for 3 years (delayed due to covid) and it's been working great, but the latest update now seems to direct me to a non-existent public facing page on my website therefore getting a 404, every time I try to order/sort my responses via any of the column titles (Attendee, RSVP Date, RSVP Status etc).

Makes it almost impossible to specifically look at new responses to the system and have to export then manually check each log against a previous export to find who is new and if anything has changed.

**Comment by cristianraiber** [comment]
cc @TeoAlex

**Comment by LiviaButtons** [comment]
@TeoAlex tested your solution locally and works perfectly. Subsequently deployed the change to live eproduction nvironment, and it works there as well. Thanks!

**Comment by GitSlinger** [comment]
@TeoAlex this also worked great for me! Thanks so much for the quick fix!
